### Project specific config ###
environment:
  APM_TEST_PACKAGES: language-asciidoc autocomplete-asciidoc asciidoc-preview
  ATOM_LINT_WITH_BUNDLED_NODE: "true"

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

# NOTE: AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci] or [skip appveyor]
skip_commits:
  author: asciidoctor-docbot

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
